# Instance methods

*	text(t)
*	empty()
*	value(v)
*	html(html)
*	getHtml()
*	getValue()
*	getText()
*	addClass(name)
*	removeClass(name)
*	hasClass(name)
*	hide()
*	show()
*	style(prop, val)
*	css(styles)
*	bind(type, callback, capture)
*	unbind(type, callback)
*	click(callback)
*	attr(key, val)
*	attributes(propList)
*	data(name, val)
*	isChecked()
*	remove()
*	text()
*	empty()
*	value()
*	html()
*	getHtml()
*	getValue()
*	getText()
*	addClass()
*	removeClass()
*	hasClass()
*	hide()
*	show()
*	style()
*	css()
*	bind()
*	unbind()
*	click()
*	attr()
*	attributes()
*	data()
*	isChecked()
*	isAnyChecked()
*	lenght()
*	get(index)
*	find(selector)
*	each(callback)
*	delegate(type, callback)
*	prepend()
*	append()

# Static methods

*	getStyle(elem, name)
*	el(tagName, className = false, props = {})
*	extend(origin, mixedIn)
*	ready(fn)